### ISSUE TITLE
Digests seem incorrect

### ISSUE THREAD

**Issue by KaiserKarel** [LucianoBestia/cargo_crev_reviews_workspace#3]
For every review created through the GUI, I am getting digest mismatched (also from the crates reviewed by @LucianoBestia, which I assume are through the GUI as well). Re reviewing them through the CLI fixes the digest.

https://github.com/crev-dev/cargo-crev/discussions/459

**Comment by LucianoBestia** [comment]
Thanks. I am working on it now. Sometimes the dependency crate's source code becomes "unclean". I don't know why that happens. That sounds like a potential for supply chain attacks.
With `dpc` we are looking to create the digest from a "clean" crate. I hope to solve this soon.

**Comment by dpc** [comment]
Note: the reason why these sources become `unclean` is that code editors one uses to open them tend to add some extra files. That's why `cargo-crev` does some stuff to clean it up before calculating the checksum.

**Comment by LucianoBestia** [comment]
So the act of reviewing the source code with a code editor is "corrupting" the code: adding the `target` folder and `Cargo.lock` file. Once in a code editor, it is even possible that the user unknowingly changes some code or comment. That is not comfortable.
I will copy the code into a temporary folder before opening the code editor. So the original will remain unchanged.

**Comment by dpc** [comment]
Sounds good!

**Comment by KaiserKarel** [comment]
Thanks for handling this so rapidly, love the GUI tool.

**Comment by LucianoBestia** [comment]
The new version v2022.122.1621 does not open VSCode in the `cargo registry src` folder, to avoid altering the crate source code with the `target` folder and `Cargo.lock` file. This happens because RustAnalyzer (IDE support , intellisense) runs `cargo check` to use its artifacts.
Now cargo_crev_reviews unpacks the .crate file into a temporary directory. No matter what happens, it will be eventually deleted and does not touch the original `cargo registry src` directory.
To correct the already miscalculated digest from existing reviews I added in `Config and utils` some integrity checks.
Use it orderly one by one. There is also a description of what they do.

**Comment by LucianoBestia** [comment]
To @KaiserKarel,  I added your proof repo to https://web.crev.dev.
